import TabMatcher, { Entry } from '../src/TabMatcher'

const anime = {
  active: false,
  audible: false,
  autoDiscardable: true,
  discarded: false,
  favIconUrl: 'https://static.hdslb.com/images/favicon.ico',
  height: 937,
  highlighted: false,
  id: 281,
  incognito: false,
  index: 0,
  mutedInfo: { muted: false },
  pinned: false,
  selected: false,
  status: 'complete',
  title: '番剧 - 哔哩哔哩 (゜-゜)つロ 干杯~-bilibili',
  url: 'https://www.bilibili.com/anime/',
  width: 1920,
  windowId: 272,
}
const chuanliushaonv = {
  active: false,
  audible: false,
  autoDiscardable: true,
  discarded: false,
  favIconUrl: 'https://static.hdslb.com/images/favicon.ico',
  height: 937,
  highlighted: false,
  id: 292,
  incognito: false,
  index: 2,
  mutedInfo: { muted: false },
  pinned: false,
  selected: false,
  status: 'complete',
  title: '川柳少女：第1话_番剧_bilibili_哔哩哔哩',
  url: 'https://www.bilibili.com/bangumi/play/ss26870',
  width: 1920,
  windowId: 272,
}
const jojo = {
  active: false,
  audible: false,
  autoDiscardable: true,
  discarded: false,
  favIconUrl: 'https://static.hdslb.com/images/favicon.ico',
  height: 937,
  highlighted: false,
  id: 293,
  incognito: false,
  index: 3,
  mutedInfo: { muted: false },
  pinned: false,
  selected: false,
  status: 'complete',
  title: 'JOJO的奇妙冒险 黄金之风：第1话_番剧_bilibili_哔哩哔哩',
  url: 'https://www.bilibili.com/bangumi/play/ss25681',
  width: 1920,
  windowId: 272,
}
const mix = {
  active: false,
  audible: false,
  autoDiscardable: true,
  discarded: false,
  favIconUrl: 'https://static.hdslb.com/images/favicon.ico',
  height: 937,
  highlighted: false,
  id: 294,
  incognito: false,
  index: 4,
  mutedInfo: { muted: false },
  pinned: false,
  selected: false,
  status: 'complete',
  title: 'MIX：第1话_番剧_bilibili_哔哩哔哩',
  url: 'https://www.bilibili.com/bangumi/play/ss26770',
  width: 1920,
  windowId: 272,
}
const nuannuanriji = {
  active: false,
  audible: false,
  autoDiscardable: true,
  discarded: false,
  favIconUrl: 'https://static.hdslb.com/images/favicon.ico',
  height: 937,
  highlighted: false,
  id: 295,
  incognito: false,
  index: 5,
  mutedInfo: { muted: false },
  pinned: false,
  selected: false,
  status: 'complete',
  title: '暖暖日记 4th：第3话_番剧_bilibili_哔哩哔哩',
  url: 'https://www.bilibili.com/bangumi/play/ss26878',
  width: 1920,
  windowId: 272,
}
const shuiguolanzi = {
  active: false,
  audible: false,
  autoDiscardable: true,
  discarded: false,
  favIconUrl: 'https://static.hdslb.com/images/favicon.ico',
  height: 927,
  highlighted: false,
  id: 297,
  incognito: false,
  index: 7,
  mutedInfo: { muted: false },
  pinned: false,
  selected: false,
  status: 'complete',
  title: '水果篮子 (2019)：第1话_番剧_bilibili_哔哩哔哩',
  url: 'https://www.bilibili.com/bangumi/play/ss26766',
  width: 958,
  windowId: 272,
}
const ext = {
  active: false,
  audible: false,
  autoDiscardable: true,
  discarded: false,
  favIconUrl: '',
  height: 927,
  highlighted: false,
  id: 278,
  incognito: false,
  index: 8,
  mutedInfo: { muted: false },
  pinned: false,
  selected: false,
  status: 'complete',
  title: '扩展程序',
  url: 'chrome://extensions/',
  width: 958,
  windowId: 272,
}
const quickjump = {
  active: true,
  audible: false,
  autoDiscardable: true,
  discarded: false,
  favIconUrl: '',
  height: 927,
  highlighted: true,
  id: 352,
  incognito: false,
  index: 9,
  mutedInfo: { muted: false },
  pinned: false,
  selected: true,
  status: 'complete',
  title: 'quick-jump',
  url: 'chrome-extension://njldpchedbhgnoonbgfaeffogcigokmd/quick-jump.html',
  width: 958,
  windowId: 272,
}
const testTabs = [anime, chuanliushaonv, jojo, mix, nuannuanriji, shuiguolanzi, ext, quickjump]

test('test', () => {
  expect(1 + 1).toBe(2)
  const matcher = new TabMatcher(testTabs)
  const keywords = ['番剧 - 哔哩哔哩']
  const actual = matcher.search(keywords)
  const expected: Entry[] = [
    {
      tab: anime,
      titleMatches: [{ start: 0, end: keywords[0].length }],
      urlMatches: [],
    },
  ]

  expect(actual).toEqual(expected)
})
